-- SUPERSEDED — do not run this file.
--
-- This migration was written by guessing the schema instead of verifying it
-- (expected_date instead of expected_at, status 'open' instead of the real
-- draft/ordered/partially_received/received/cancelled vocabulary, a
-- movement_type CHECK missing 'consumption', and a from-scratch redefinition
-- of stock_dashboard that ignored the real stock_physical / stock_ordered /
-- stock_reserved views). It was run against Supabase before being caught.
--
-- Introspection of the live DB afterwards showed:
--   - suppliers, supplier_orders, supplier_order_lines already existed with
--     the correct structure before this file was ever written — the
--     `create table if not exists` statements below were no-ops.
--   - The movement_type CHECK and the stock_dashboard view were NOT
--     actually altered (Postgres appears to have stopped committing once
--     the run hit the erroring DROP/CREATE VIEW statement) — both are
--     still in their correct original state.
--   - The RLS policies section below DID commit, leaving 7 redundant
--     policies duplicating the pre-existing "Members can manage X" ones.
--
-- The content has been removed so this file can never be accidentally
-- re-run (e.g. against a fresh database) and reintroduce the same bugs.
-- The actual corrective changes are in
-- 20260817_supplier_orders_fix.sql — see that file for what was really
-- needed and why.
